#!/bin/bash
# Script to install build dependencies for liblognorm on Ubuntu
# Generated by AI Agent

set -e

echo "Updating package lists..."
sudo apt-get update

echo "Installing build tools..."
sudo apt-get install -y \
    build-essential \
    autoconf \
    automake \
    libtool \
    pkg-config \
    git

echo "Installing library dependencies..."
sudo apt-get install -y \
    libestr-dev \
    libfastjson-dev \
    libpcre3-dev

echo "Installing documentation tools..."
sudo apt-get install -y \
    python3-sphinx

echo "Dependencies installed successfully."
